Add Portuguese Brazilian translation
openmultiplayer/launcher pull request #21
Opened 2023-11-12 17:04 UTC by gHenriqueCarlos

2023-11-12 17:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openmultiplayer/launcher?pullRequest=21) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openmultiplayer/launcher?pullRequest=21) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openmultiplayer/launcher?pullRequest=21) it.</sub>

2023-11-12 17:11 UTC, LESS14 reviewed
There's no need to name it "ptbr" since, in this grammar, there's no distinction between European Portuguese and Brazilian Portuguese. For better understanding, rename it as "pt".

2023-11-12 17:19 UTC, pkfln commented
> There's no need to name it "ptbr" since, in this grammar, there's no distinction between European Portuguese and Brazilian Portuguese. For better understanding, rename it as "pt".

There definitely are differences. The correct locale is pt-BR for this one.

2023-11-12 17:21 UTC, LESS14 requested changes

2023-11-12 17:21 UTC, LESS14 commented on src/locales/translations/ptbr.ts
> +  address: "Endereço",
Change this part to "Endereço IP".

2023-11-12 17:21 UTC, LESS14 commented on src/locales/translations/ptbr.ts
> +  settings_import_nickname_gta_path_from_samp:
Change this part to "Importar configurações do SA-MP"

2023-11-12 17:21 UTC, LESS14 commented on src/locales/translations/ptbr.ts
> +  settings_new_update_available: "⚠ Nova atualização disponível. Clique para fazer o download! ⚠",
Change this part to "⚠ Nova atualização disponível. Clique aqui para baixar a atualização! ⚠"

2023-11-12 17:21 UTC, LESS14 commented on src/locales/translations/ptbr.ts
> +  settings_credits_view_source_on_github: "Veja o código-fonte no GitHub",
Change this part to "Código fonte disponível no GitHub"

2023-11-12 17:21 UTC, LESS14 commented on src/locales/translations/ptbr.ts
> +  update_modal_remind_me_next_time: "Me lembre na próxima vez",
Change this part to "Me lembre mais tarde"

2023-11-12 17:23 UTC, LESS14 commented
> > There's no need to name it "ptbr" since, in this grammar, there's no distinction between European Portuguese and Brazilian Portuguese. For better understanding, rename it as "pt".
> 
> There definitely are differences between European and Brazilian Portuguese. The correct locale is pt-BR for this one.

Not in this case, since this grammar can be easily understood by both accents.

2023-11-12 17:27 UTC, pkfln commented
I just skimmed through it and as someone that learned European Portuguese, I wouldn't have known what they meant by "Apelido" in this case. I've only seen username/nickname/alcunha/usario being used.

2023-11-12 17:31 UTC, gHenriqueCarlos commented
> I just skimmed through it and as someone that learned European Portuguese, I wouldn't have known what they meant by "Apelido" in this case. I've only seen username/nickname/alcunha/usario being used.

We can replace 'Apelido' with 'Nome de Usuário' or just 'Usuário.' I believe it will work well for both. What do you think?

2023-11-12 17:37 UTC, LESS14 commented
> We can replace 'Apelido' with 'Nome de Usuário' or just 'Usuário.' I believe it will work well for both. What do you think?

It would be better, in my opinion, since it would make it easier for both European Portuguese and Brazilian Portuguese to understand.

2023-11-12 17:59 UTC, LESS14 approved these changes

2023-11-12 19:54 UTC, pushline approved these changes

2023-11-13 09:56 UTC, Southclaws approved these changes
Muito bom, obrigado!

2023-11-13 09:57 UTC, merged